server:
  port: 8888
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
       mvc:
        routes:
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/orders/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
          - Path=/inventory/**

        - id: google-test
          uri: http://www.google.co.in
          predicates:
           - Path=/redirect/**


#http://localhost:9090/redirect/ --->http://www.google.co.in

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
